# Generated by Django 5.2.8 on 2025-11-30 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='classdataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('niveau_etude', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('affectation', models.CharField(max_length=200)),
                ('annee_ambauche', models.CharField(max_length=200)),
                ('salaire_cat', models.TextField()),
                ('gender', models.CharField(max_length=200)),
                ('experience_domain', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predections', to=settings.AUTH_USER_MODEL, verbose_name='predection')),
            ],
            options={
                'verbose_name': 'predection',
                'verbose_name_plural': 'predection',
                'ordering': ['-date_creation'],
            },
        ),
    ]
