# Generated by Django 5.2.8 on 2025-12-01 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoAi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classdataset',
            options={'ordering': ['-date_creation'], 'verbose_name': 'predection', 'verbose_name_plural': 'predections'},
        ),
        migrations.AddField(
            model_name='classdataset',
            name='target',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='classdataset',
            name='salaire_cat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='classdataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL, verbose_name='predection'),
        ),
    ]
