# Generated by Django 5.2.8 on 2025-12-01 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoAi', '0002_alter_classdataset_options_classdataset_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('age', models.FloatField(verbose_name='Âge')),
                ('gender', models.CharField(max_length=50, verbose_name='Genre')),
                ('weight', models.FloatField(verbose_name='Poids (kg)')),
                ('height', models.FloatField(verbose_name='Taille (cm)')),
                ('bmi', models.FloatField(verbose_name='IMC')),
                ('fat_percentage', models.FloatField(verbose_name='Pourcentage de graisse (%)')),
                ('max_bpm', models.FloatField(verbose_name='BPM Maximum')),
                ('avg_bpm', models.FloatField(verbose_name='BPM Moyen')),
                ('resting_bpm', models.FloatField(verbose_name='BPM au repos')),
                ('session_duration', models.FloatField(verbose_name='Durée session (min)')),
                ('workout_type', models.CharField(max_length=100, verbose_name="Type d'entraînement")),
                ('water_intake', models.FloatField(verbose_name="Consommation d'eau (L)")),
                ('workout_frequency', models.FloatField(verbose_name="Fréquence d'entraînement (jours/semaine)")),
                ('experience_level', models.IntegerField(verbose_name="Niveau d'expérience")),
                ('target', models.CharField(blank=True, default='', max_length=200, verbose_name='Résultat')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_predictions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Prédiction Fitness',
                'verbose_name_plural': 'Prédictions Fitness',
                'ordering': ['-date_creation'],
            },
        ),
    ]
